# These are supported funding model platforms

github: [xgqfrms]
patreon: xgqfrms
open_collective: xgqfrms
ko_fi: xgqfrms
tidelift: npm/visual-vode-generator
community_bridge: Visual-Code-Generator
liberapay: xgqfrms
issuehunt: xgqfrms
otechie: xgqfrms
custom: ['https://visual-vode-generator.xgqfrms.xyz/']
